# Generated by Django 3.2 on 2021-06-05 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.hall'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
