# Generated by Django 3.2 on 2021-06-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0003_auto_20210606_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='sex',
        ),
    ]
