# Generated by Django 3.2 on 2021-06-08 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0004_remove_actor_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Discount',
            },
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['id']},
        ),
    ]
