# Generated by Django 3.2 on 2021-04-09 03:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0004_remove_actor_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='price',
        ),
        migrations.AddField(
            model_name='projection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projection',
            name='monetary cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='projection',
            name='partner points cost',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='projection',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cinema.time'),
        ),
    ]
