# Generated by Django 3.2 on 2021-04-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0005_auto_20210608_1039'),
        ('Cinema', '0006_auto_20210409_0044'),
    ]

    operations = [
    ]
