# Generated by Django 3.2 on 2021-04-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0007_merge_0005_auto_20210608_1039_0006_auto_20210409_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('discounts', models.CharField(max_length=100)),
                ('entries', models.ManyToManyField(to='Cinema.Entry')),
            ],
        ),
    ]
