# Generated by Django 3.2 on 2021-06-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0008_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='discounts',
        ),
        migrations.AddField(
            model_name='purchase',
            name='discounts',
            field=models.ManyToManyField(to='Cinema.Discount'),
        ),
    ]
