# Generated by Django 3.2 on 2021-06-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0009_auto_20210611_1256'),
        ('Cinema', '0009_auto_20210611_1549'),
    ]

    operations = [
    ]
